spring.application.name=rds

server.port = 8081

spring.datasource.url = jdbc:mysql://admin@policy-database-instance.cd880esy4tgf.ap-south-1.rds.amazonaws.com:3306/policy?createDatabaseIfNotExist=true
spring.datasource.username = admin
spring.datasource.password = manager147

spring.jpa.hibernate.ddl-auto = update